# Generated by Django 6.1 on 2026-09-11 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsidePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(choices=[('photography', 'Photography'), ('travel', 'Travel'), ('runs', 'Runs')], default='photography', max_length=20)),
                ('album', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('taken_at', models.DateField(blank=True, null=True)),
                ('is_hero', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'album', 'order'],
            },
        ),
    ]
