# Generated by Django 6.1 on 2026-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seed_outside_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['company_order', 'order']},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('organization', 'Organization'), ('committee', 'Committee')], default='volunteer', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
