# Generated by Django 6.1 on 2026-09-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='link_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link_2_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('case-competition', 'Case Competition'), ('business-plan', 'Business Plan Competition'), ('hackathon', 'Hackathon'), ('personal', 'Personal Project'), ('coursework', 'Coursework')], default='personal', max_length=30),
        ),
    ]
