# Generated by Django 6.1 on 2026-09-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fix_project_image_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
